api:
  id: "20404369"
http:
  port: "8081"
sender:
  name: "FUNDPANEL"
receiver:
  name: "DATACLOUD"
division: "FUNDPANEL-INTEGRATION-SERVICES"
index:
  name: "logs_datasync_mulesoft"
business:
  group: "IT"  
  
maxRecords: "2000"
maxPages: "10000"

sfdc:
  connection:
    timeout: "120"
  reconnect:
    frequency: "3000"
    attempts: "2"
  tokenendpoint: "https://login.salesforce.com/services/oauth2/token"
  demo:
    username: "bz+fundpaneldemo@nteligroup.com"
    consumerkey: "3MVG92bg6BUCmlUby5YQPX6UTNdwdE5p86KSWdVH2bFB6sAnTDfxKhlwFGyoUP9H3QyprnRnyqKjEYaVVYrDw"
    tokenendpoint: "https://test.salesforce.com/services/oauth2/token"
    orgId: "00DDk000000EA8XMAW"
  signalfire:
    username: "bz@nteligroup.com.signalfire-pilot"
    consumerkey: "3MVG9fMtCkV6eLhcqmpDEUwO1jIw_w1qcR.fAlb3o62ijFcj_MFMc3CW7wKe45ZBrXOhpYftCOahmrfk9i_rW"
    orgId: "00Dj0000000HhuKEAS"
  caffeinatedcapital:
    username: "bz@nteligroup.com.cafcap-pilot"
    consumerkey: "3MVG9sG9Z3Q1Rlbe5kI8K75NxVMy4uEHY.KDLD3dG0NYsqmZHbF.ODghrmlbz7su281pUKLjCgRqn1.IR8vhL"
    orgId: "00D1a000000HHqEEAW"
  lowercarboncapital:
    username: "bz@nteligroup.com.lowercarbon-pilot"
    consumerkey: "3MVG9Nk1FpUrSQHfXclJ9fuqXHmrYiGiVbxZRXw4A.i8ydPqh_pUwBG6ZwNPoS2T84QFHmov60xxqkMJ8xD2A"
    orgId: "00D5Y000002W93zUAC"  
  nextlegacy:
    username: "bz@nteligroup.com.nextlegacy-pilot"
    consumerkey: "3MVG9zlTNB8o8BA3waukRqcgFxatBJEAihcdOTwfSOlrr2EBiUvTd.WXxW2538HvhJWNCBkMZCPDNPc.wNCfd"
    orgId: "00Df40000000v6aEAA" 
  susaventures:
    username: "bz@nteligroup.com.susa-pilot"
    consumerkey: "3MVG9fMtCkV6eLhdnDBGvTR1TJPZzoo1NtVxdSYONQTXK8f3QAxlT3sP.lXbLMf_Wx.GiwmXyvkrM4p8pojXt"
    orgId: "00Dj0000001msAMEAY"
  goodwater:
    username: "bz@nteligroup.com.goodwater-pilot"
    consumerkey: "3MVG9QDx8IX8nP5Rg.yiMPaeRdTtF78mjtISxQvg1bZHKSvchhIjMoLa0PbBjJ7W4lrxbknEF4WqQ_TKSuOEJ"
    orgId: "00DU0000000MH3TMAW"
  blingcapital:
    username: "bz@nteligroup.com.bling-pilot"
    consumerkey: "3MVG9vrJTfRxlfl6SZMrgFX_RMACqbAgu4Hw0xBPvgglFfCXKsfp62HE9U4gtS2AzPpyOvuc5q4pNiOMAM.hh"
    orgId: "00D5A000000BnLcUAK"
  seaxventures:
    username: "bz@nteligroup.com.seax-pilot"
    consumerkey: "3MVG9_XwsqeYoueII31yLLiNqzotmYEXPBY9VvK5xhju0LhmrIJbNkBC5818p6zrI1ubM7.r6vW_I4zAfXzgJ"
    orgId: "00D5A000000BnLcUAK"
  craftventures:
    username: "bz@nteligroup.com.craft-pilot"
    consumerkey: "3MVG9zlTNB8o8BA1A99mfpO53WPNH78A6WapVBvmqDuP8EV0oRC.nq08rjfMYPWOJ5q95LUSoVm4o27yvLRUD"
    orgId: "00Df4000003kiGBEAY"
  primemoverslab:
    username: "bz@nteligroup.com.primemovers-pilot"
    consumerkey: "3MVG9dZJodJWITStShQVUtojA3qI5WegYJnWeTKebfnhioMnX3YA36EQprz9zeuWtKmCbqCuPDhXLcXk7cU7j"
    orgId: "00D0b000000E30hEAC"

anypointmq:
  url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/3b8fd8b9-8002-4652-99bf-99d1c946b0ee/environments/f682e196-03c9-493a-ba10-299236acb7a9"
  salesforceExchange: "aduro-nonprod-sfdc-exchange"
  clientId: "a3d5f7e3fdcb4c22abb0c1c8ecdaf477"  
  
request:
  max.retries: "2"
  retry.interval.millisec: "6000"
