sfdc:
  password: "![MO1Dnbe21qGWX6psBtW4FQ==]"
  token: "![ikjnjJCIYSqEHGq4UZUBRcpBZpwpDgKnEvGn99skzK0=]"
  consumersecret: "![y1XAncBpuhpZXR+M1NlTXZOgK2WHxWRDrrzUwF0s6EJDgr0vw6bMsCDnC9LZqGQO3h+Zx1G4jI/G4SWuuf90HzLAdTStmQyLLhn+fAlu/38=]"

anypointmq:
  clientSecret: "![5qr08e0jQ/YCTfUG6xUuyIufaQ/RaEq1VXzxUWs5loGxXSMxciUdexawRzQq7Rmf]"