sfdc:
  consumerkey: "![SwC7DrX1QHTxy/96yY1WC7/3YpqxJB4bm3QrXGVzEbFXxFnJMIM2cSCbmUwZbGKutf2ZEnSX0eG5GcifKB6oiKUEJz7qBYg2/lMvh5IproY/XJYufMQ/CqkVuP/J2pTm]"
  password: "![ZSvv9uiVg7WjmlngZtiXDP22JNpCMphZejjulv4g1lg=]"
  
anypointmq:
  clientSecret: "![5qr08e0jQ/YCTfUG6xUuyIufaQ/RaEq1VXzxUWs5loGxXSMxciUdexawRzQq7Rmf]"